# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

 platform :ios, '8.0'

target 'CGComBox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CGComBox

   pod 'Masonry'


  target 'CGComBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CGComBoxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
